version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['http://localhost:8080']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization']
