apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-conf
  namespace: exam
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }