spring:
    application:
        name: backend

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    datasource:
        url: jdbc:postgresql://localhost:5432/BackendDb
        username: postgres
        password: Demmahom102938
        driver-class-name: org.postgresql.Driver

server:
    port: 8080