spring:
    application:
        name: backend

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    datasource:
        url: jdbc:postgresql://${DB_HOST:postgres-container}:${DB_PORT:5432}/${DB_NAME:my_database}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres123}
        driver-class-name: org.postgresql.Driver

server:
    port: 8080