apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: exam
spec:
  serviceName: postgres-service
  replicas: 2
  selector: 
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres 
          lifecycle:
            preStop:
              exec: 
                command:
                  - /pre-stop.sh
          image: docker.io/bitnami/